# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    standard_helpers:       [Partial, Cache, I18N]
      
    #i18n
    charset: utf-8
    i18n: true
    #default_culture: en_US
    
    # Form security secret (CSRF protection)
    csrf_secret:            f077070530d40e5a902ad50aee4e88626b5a45ac

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true
    
    #sfGuard Config
    sf_guard_plugin:
      routes_register: false
      
    enabled_modules:      [default, sfGuardAuth, sfGuardGroup, sfGuardUser, sfGuardPermission]
    login_module:         sfGuardAuth
    login_action:         signin
    
    secure_module:        sfGuardAuth
    secure_action:        secure


