<?php

/**
 * ChoiceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChoiceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChoiceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Choice');
    }
}