<?php

/**
 * ContestChoiceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContestChoiceTable extends ChoiceTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContestChoiceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContestChoice');
    }
}