<?php

/**
 * Contest
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    sms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Contest extends BaseContest{
	
	public function addData($cid, $person){
		$cd = new ConestData();
		$cd->Person = $person;
		$q = Doctrine_Query::create()->select('*')->from('ContestData cd')
				->orderBy('cd.id ACS')->fetchArray();
		$cd->Choice = $q[$cid];
		$cd->save();
	}
}
