<?php

/**
 * ContestDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContestDataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContestDataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContestData');
    }
}