<?php

/**
 * ElectionChoiceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ElectionChoiceTable extends ChoiceTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ElectionChoiceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ElectionChoice');
    }
}