<?php

/**
 * ElectionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ElectionTable extends ProgramTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ElectionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Election');
    }
}