<?php

/**
 * ElectionDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ElectionDataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ElectionDataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ElectionData');
    }
}