<?php

/**
 * GlobalSMSTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GlobalSMSTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GlobalSMSTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GlobalSMS');
    }
}