<?php

/**
 * GroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Group');
    }
	public function getAllAsArray()
    {
    	return $this->findAll();//Doctrine_Core::HYDRATE_ARRAY);
        //return Doctrine_Core::getTable('Group');
    }
}