<?php

/**
 * GroupPersonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupPersonTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupPersonTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GroupPerson');
    }
}