<?php

/**
 * PollDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PollDataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PollDataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PollData');
    }
}