<?php

/**
 * ProgramDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProgramDataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProgramDataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProgramData');
    }
}