<?php

/**
 * ProgramTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProgramTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProgramTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Program');
    }
}