<?php

/**
 * RegisterDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RegisterDataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RegisterDataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RegisterData');
    }
}