<?php

/**
 * RegisterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RegisterTable extends ProgramTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object RegisterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Register');
    }
}