<?php

/**
 * ResponderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResponderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResponderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Responder');
    }
}