<?php

/**
 * Sent
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    sms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Sent extends BaseSent
{
	public function resend()
	{
		SMS::send(new PQL($this->getReceiver()),$this->getText());
	}
	public function email()
	{
		//TODO parse reciver
		$person = PersonTable::getInstance()->findOneByPhone($this->getReceiver());
		EMail::send(new PQL($person->getEmail()),'Emailed form SMS system',$this->getText());
	}
}
