<?php

/**
 * SentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sent');
    }
//public  function getIsnstance()
//    {
//    	$this->fi
//        return Doctrine_Core::getTable('Sent');
//    }
}