<?php

/**
 * StatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Status');
    }
}