<?php

/**
 * UserDetailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserDetailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserDetailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserDetail');
    }
}