<?php

/**
 * sfGuardUser
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    sms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
	private $charge= 0;
	public function alterCharge($amount){
		$this->charge += $amount;
	}
	public function canSend($amount){
		return ($this->getCharge() - $amount>=0);
	}
	public function getCharge(){
		return 0;
	}
	public function setCharge($amount){
		$this->char;
	}
}
