generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Sent
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sent
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        batch_actions:
          _delete:    ~
          resend:     ~
          sendByEmail:     ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
