<?php

/**
 * BaseStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Messages
 * 
 * @method string              getName()     Returns the current record's "name" value
 * @method Doctrine_Collection getMessages() Returns the current record's "Messages" collection
 * @method Status              setName()     Sets the current record's "name" value
 * @method Status              setMessages() Sets the current record's "Messages" collection
 * 
 * @package    sms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('status');
        $this->hasColumn('name', 'string', 25, array(
             'type' => 'string',
             'length' => 25,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Sent as Messages', array(
             'local' => 'id',
             'foreign' => 'status_id'));
    }
}