<?php

/**
 * BaseUserDetail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property double $charge
 * @property string $phone
 * @property sfGuardUser $User
 * 
 * @method integer     getUserId()  Returns the current record's "user_id" value
 * @method double      getCharge()  Returns the current record's "charge" value
 * @method string      getPhone()   Returns the current record's "phone" value
 * @method sfGuardUser getUser()    Returns the current record's "User" value
 * @method UserDetail  setUserId()  Sets the current record's "user_id" value
 * @method UserDetail  setCharge()  Sets the current record's "charge" value
 * @method UserDetail  setPhone()   Sets the current record's "phone" value
 * @method UserDetail  setUser()    Sets the current record's "User" value
 * 
 * @package    sms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserDetail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_detail');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('charge', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('phone', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}