<?php

/**
 * BaseContest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $winners_count
 * @property integer $answer_id
 * @property boolean $auto_result
 * @property boolean $performed
 * @property ContestChoice $Answer
 * @property Doctrine_Collection $Choices
 * 
 * @method integer             getWinnersCount()  Returns the current record's "winners_count" value
 * @method integer             getAnswerId()      Returns the current record's "answer_id" value
 * @method boolean             getAutoResult()    Returns the current record's "auto_result" value
 * @method boolean             getPerformed()     Returns the current record's "performed" value
 * @method ContestChoice       getAnswer()        Returns the current record's "Answer" value
 * @method Doctrine_Collection getChoices()       Returns the current record's "Choices" collection
 * @method Contest             setWinnersCount()  Sets the current record's "winners_count" value
 * @method Contest             setAnswerId()      Sets the current record's "answer_id" value
 * @method Contest             setAutoResult()    Sets the current record's "auto_result" value
 * @method Contest             setPerformed()     Sets the current record's "performed" value
 * @method Contest             setAnswer()        Sets the current record's "Answer" value
 * @method Contest             setChoices()       Sets the current record's "Choices" collection
 * 
 * @package    sms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContest extends Program
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('contest');
        $this->hasColumn('winners_count', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('answer_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('auto_result', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('performed', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ContestChoice as Answer', array(
             'local' => 'answer_id',
             'foreign' => 'id'));

        $this->hasMany('ContestChoice as Choices', array(
             'local' => 'id',
             'foreign' => 'contest_id'));
    }
}