<?php

/**
 * BaseRegisterData
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $register_id
 * @property Register $Register
 * 
 * @method integer      getRegisterId()  Returns the current record's "register_id" value
 * @method Register     getRegister()    Returns the current record's "Register" value
 * @method RegisterData setRegisterId()  Sets the current record's "register_id" value
 * @method RegisterData setRegister()    Sets the current record's "Register" value
 * 
 * @package    sms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegisterData extends ProgramData
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('register_data');
        $this->hasColumn('register_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Register', array(
             'local' => 'register_id',
             'foreign' => 'id'));
    }
}