<?php

/**
 * BaseGlobalSMS
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $sender
 * @property text $text
 * @property boolean $unread
 * 
 * @method string    getSender() Returns the current record's "sender" value
 * @method text      getText()   Returns the current record's "text" value
 * @method boolean   getUnread() Returns the current record's "unread" value
 * @method GlobalSMS setSender() Sets the current record's "sender" value
 * @method GlobalSMS setText()   Sets the current record's "text" value
 * @method GlobalSMS setUnread() Sets the current record's "unread" value
 * 
 * @package    sms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGlobalSMS extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('global_s_m_s');
        $this->hasColumn('sender', 'string', 25, array(
             'type' => 'string',
             'length' => 25,
             ));
        $this->hasColumn('text', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('unread', 'boolean', null, array(
             'type' => 'boolean',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}