<?php

/**
 * BaseProgram
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $code
 * @property timestamp $start
 * @property timestamp $end
 * @property string $participants
 * @property integer $responder_id
 * @property Responder $Responder
 * 
 * @method string    getName()         Returns the current record's "name" value
 * @method integer   getCode()         Returns the current record's "code" value
 * @method timestamp getStart()        Returns the current record's "start" value
 * @method timestamp getEnd()          Returns the current record's "end" value
 * @method string    getParticipants() Returns the current record's "participants" value
 * @method integer   getResponderId()  Returns the current record's "responder_id" value
 * @method Responder getResponder()    Returns the current record's "Responder" value
 * @method Program   setName()         Sets the current record's "name" value
 * @method Program   setCode()         Sets the current record's "code" value
 * @method Program   setStart()        Sets the current record's "start" value
 * @method Program   setEnd()          Sets the current record's "end" value
 * @method Program   setParticipants() Sets the current record's "participants" value
 * @method Program   setResponderId()  Sets the current record's "responder_id" value
 * @method Program   setResponder()    Sets the current record's "Responder" value
 * 
 * @package    sms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProgram extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('program');
        $this->hasColumn('name', 'string', 25, array(
             'type' => 'string',
             'length' => 25,
             ));
        $this->hasColumn('code', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('start', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('end', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('participants', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('responder_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Responder', array(
             'local' => 'responder_id',
             'foreign' => 'id'));
    }
}