<?php

/**
 * BaseProgramData
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $person_id
 * @property Person $Person
 * 
 * @method integer     getPersonId()  Returns the current record's "person_id" value
 * @method Person      getPerson()    Returns the current record's "Person" value
 * @method ProgramData setPersonId()  Sets the current record's "person_id" value
 * @method ProgramData setPerson()    Sets the current record's "Person" value
 * 
 * @package    sms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProgramData extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('program_data');
        $this->hasColumn('person_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Person', array(
             'local' => 'person_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}