<?php

/**
 * BaseGroupPerson
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $group_id
 * @property integer $person_id
 * @property Group $Group
 * @property Person $Person
 * 
 * @method integer     getGroupId()   Returns the current record's "group_id" value
 * @method integer     getPersonId()  Returns the current record's "person_id" value
 * @method Group       getGroup()     Returns the current record's "Group" value
 * @method Person      getPerson()    Returns the current record's "Person" value
 * @method GroupPerson setGroupId()   Sets the current record's "group_id" value
 * @method GroupPerson setPersonId()  Sets the current record's "person_id" value
 * @method GroupPerson setGroup()     Sets the current record's "Group" value
 * @method GroupPerson setPerson()    Sets the current record's "Person" value
 * 
 * @package    sms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGroupPerson extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('group_person');
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('person_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Group', array(
             'local' => 'group_id',
             'foreign' => 'id'));

        $this->hasOne('Person', array(
             'local' => 'person_id',
             'foreign' => 'id'));
    }
}