<?php

/**
 * BaseContestData
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $choice_id
 * @property ContestChoice $Choice
 * 
 * @method integer       getChoiceId()  Returns the current record's "choice_id" value
 * @method ContestChoice getChoice()    Returns the current record's "Choice" value
 * @method ContestData   setChoiceId()  Sets the current record's "choice_id" value
 * @method ContestData   setChoice()    Sets the current record's "Choice" value
 * 
 * @package    sms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContestData extends ProgramData
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('contest_data');
        $this->hasColumn('choice_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ContestChoice as Choice', array(
             'local' => 'choice_id',
             'foreign' => 'id'));
    }
}