<?php

/**
 * BaseRegister
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $capacity
 * @property Doctrine_Collection $RegisterData
 * 
 * @method integer             getCapacity()     Returns the current record's "capacity" value
 * @method Doctrine_Collection getRegisterData() Returns the current record's "RegisterData" collection
 * @method Register            setCapacity()     Sets the current record's "capacity" value
 * @method Register            setRegisterData() Sets the current record's "RegisterData" collection
 * 
 * @package    sms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegister extends Program
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('register');
        $this->hasColumn('capacity', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('RegisterData', array(
             'local' => 'id',
             'foreign' => 'register_id'));
    }
}