<?php

/**
 * BasePattern
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $text
 * @property string $field
 * 
 * @method string  getText()  Returns the current record's "text" value
 * @method string  getField() Returns the current record's "field" value
 * @method Pattern setText()  Sets the current record's "text" value
 * @method Pattern setField() Sets the current record's "field" value
 * 
 * @package    sms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePattern extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pattern');
        $this->hasColumn('text', 'string', 25, array(
             'type' => 'string',
             'length' => 25,
             ));
        $this->hasColumn('field', 'string', 25, array(
             'type' => 'string',
             'length' => 25,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}