<?php

/**
 * BaseContestChoice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $contest_id
 * @property Contest $Contest
 * @property Contest $AnswerOfContest
 * @property Doctrine_Collection $ContestData
 * 
 * @method integer             getContestId()       Returns the current record's "contest_id" value
 * @method Contest             getContest()         Returns the current record's "Contest" value
 * @method Contest             getAnswerOfContest() Returns the current record's "AnswerOfContest" value
 * @method Doctrine_Collection getContestData()     Returns the current record's "ContestData" collection
 * @method ContestChoice       setContestId()       Sets the current record's "contest_id" value
 * @method ContestChoice       setContest()         Sets the current record's "Contest" value
 * @method ContestChoice       setAnswerOfContest() Sets the current record's "AnswerOfContest" value
 * @method ContestChoice       setContestData()     Sets the current record's "ContestData" collection
 * 
 * @package    sms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContestChoice extends Choice
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('contest_choice');
        $this->hasColumn('contest_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Contest', array(
             'local' => 'contest_id',
             'foreign' => 'id'));

        $this->hasOne('Contest as AnswerOfContest', array(
             'local' => 'id',
             'foreign' => 'answer_id'));

        $this->hasMany('ContestData', array(
             'local' => 'id',
             'foreign' => 'choice_id'));
    }
}